version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-express-network
    tty: true
    ports:
      - "8080:80"

  node-express:
    build:
      context: ./node
    container_name: node-express
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on:
      - db
    networks:
      - node-express-network
    volumes:
      - ./node:/usr/src/app
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-express-network

networks:
  node-express-network:
    driver: bridge